language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
env:
  - DJANGO=1.4.10 FEINCMS=1.8.4
  - DJANGO=1.5.5 FEINCMS=1.8.4
  - DJANGO=1.6 FEINCMS=1.8.4
  - DJANGO=1.4.10 FEINCMS=1.9.2
  - DJANGO=1.5.5 FEINCMS=1.9.2
  - DJANGO=1.6 FEINCMS=1.9.2
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=1.4.10 FEINCMS=1.8.4
    - python: "3.3"
      env: DJANGO=1.4.10 FEINCMS=1.9.2
    - python: "3.2"
      env: DJANGO=1.4.10 FEINCMS=1.8.4
    - python: "3.2"
      env: DJANGO=1.5.5 FEINCMS=1.8.4
    - python: "3.2"
      env: DJANGO=1.6 FEINCMS=1.8.4
    - python: "3.2"
      env: DJANGO=1.4.10 FEINCMS=1.9.2
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q Django==$DJANGO FeinCMS==$FEINCMS django-mptt==0.6.0 factory_boy==2.2.1 pytz==2013.8 flake8 --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp && flake8 ."
